[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 12

[font.bold]
family = "InputMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "InputMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "InputMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "InputMono Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = '''(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)//[a-zA-Z0-9,'+\.\-_/\?=&%:]+'''

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "S"
mode = "~Vi|~Search"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "S"
mode = "~Vi"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "~Vi"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "PasteSelection"
key = "V"
mode = "~Vi"
mods = "Alt|Control"
